#### 1. Activate function 
##### sigmoid
$$\widehat{y}=\sigma\left(w^{T} x+b\right), \sigma(z)=\frac{1}{1+e^{-z}}$$

#### 2. Loss function describe how well a single training example performs
In order to avoid local optimal, we need to find a cost function that is convex.
$$\ell(\hat{y}, y)=-(y \log \hat{y}+(1-y) \log (1-\hat{y}))$$
##### intuition
if y==1, loss=-log(y hat), in order to let the loss function small, we need y hat to larger whereas the lagest value of y hat is 1(due to the sigmol function), so y hat should be as close as possible to 1.
Same goes to if y==0.

#### 3. Cost function describe how well the whole training set performs
$$J(w, b)=\frac{1}{m} \sum_{m=1}^{m} \mathcal{L}\left(\hat{y}^{(i)}, y^{(i)}\right)=-\frac{1}{m} \sum_{m=1}^{m} y^{(i)} \log \widehat{y}^{(i)}+\left(1-y^{(i)}\right) \log \left(1-\hat{y}^{(i)}\right)$$

#### 4. Gradient descent is a way to learn the parameters w and b
alpha is called the learning rate
$$\omega :=\omega-\alpha \frac{d J(\omega)}{d \omega}$$
Back propagation is actually calculating the the gradient descent since the gradient descent is all about partial derivitive. 

#### 5. one training example in gradient descent

#### 6. m training examples in one step of gradient descent

#### 7. vectorization

In [9]:
import numpy as np
import time

"""
np.abs
np.log
np.exp
np.maximum
"""

a = np.random.rand(1000000)
b = np.random.rand(1000000)

start = time.time()
result = np.dot(a,b)
end = time.time()
print(result)
print(f"Vectorize version: {1000*(end-start)} ms")

result = 0
start = time.time()
for x in range(len(a)):
    result+=a[x]*b[x]
end = time.time()
print(result)
print(f"For loop: {1000*(end-start)} ms")

250029.38477480848
Vectorize version: 1.6069412231445312 ms
250029.38477481078
For loop: 447.221040725708 ms


#### 8. numpy broadcasting

In [15]:
x = np.random.rand(10)
print(x)
x+100 # this will duplicate 100 to 10*1 column vector

[0.99762089 0.91231231 0.89120489 0.81176301 0.01483959 0.35683108
 0.86158341 0.5089505  0.45216609 0.84169764]


array([100.99762089, 100.91231231, 100.89120489, 100.81176301,
       100.01483959, 100.35683108, 100.86158341, 100.5089505 ,
       100.45216609, 100.84169764])

#### 9. Tips of using numpy

In [18]:
# avoid using array with rank 1
m = np.random.randn(4)
print(m)
print(m.shape) # rank 1

[-0.15983725  2.12837109 -0.7692904  -0.41988178]
(4,)


In [19]:
# insdead use 
m = np.random.randn(4,1)
print(m)
print(m.shape)

[[ 0.71208347]
 [-0.50313858]
 [ 0.18703288]
 [-0.3009337 ]]
(4, 1)


In [21]:
# reshape: essentially, the idea is to specify the num of cols and num of rows clearly
m = np.random.randn(4)
m = m.reshape((1,4))
print(m)
print(m.shape)

[[-1.4850734   0.22061856 -0.72193109  0.97893229]]
(1, 4)
